apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron1
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 4
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            parent: "cronjob1"
        spec:
          containers:
            - name: spedev
              image:  docker-registry.default.svc:5000/spe/spedev
              command: ["python",  "entry.py"]
              env:
              - name: api_dir_client_id
                value: "jjjij"
              - name: api_dir_secret
                value: "jjjjjj"
              - name: api_dir_url
                value: "https://apigw-tst.it.umich.edu/um"
              - name: course
                value: "199999"
              - name: assignment_id
                value: "256789"
              - name: persistent_path
                value: "/opt/spe-dev-persist"
              - name: logging_level
                value: "TRACE"
              - name: file_name
                value: "persisted.txt"
              - name: smpt_host
                value: "vdc-relay.us-east-2.a.mail.umich.edu"
              - name: smpt_port
                value: "587"
              - name: smpt_to
                value: "tl-spe-email-test@umich.edu"
              - name: smpt_from
                value: "tl-spe-email-test@umich.edu"
              - name: smpt_debug
                value: "1"
              volumeMounts:
                - mountPath: /opt/spe-dev-persist
                  name: spe-dev-persist-vol
          volumes:
            - name: spe-dev-persist-vol
              persistentVolumeClaim:
                claimName: spe-dev-persist
          restartPolicy: OnFailure